model:
  dim: 16
  dim_mults: [1, 2, 4, 8]
  num_classes: 1
  cond_drop_prob: 0.0
  input_dim: 9
  condition_dim: 12
  out_dim: 3

diffusion:
  image_size: 256
  timesteps: 1000
  sampling_timesteps: 25
  beta_schedule: linear
  objective: pred_x0

dataset:
  name: fastec
  train_path: /data/fastec/Fastec/train
  test_path: /data/fastec/Fastec/test

trainer:
  train_batch_size: 1
  train_lr: 0.0001
  train_num_steps: 150000
  gradient_accumulate_every: 16
  ema_decay: 0.995
  amp: False
  save_and_sample_every: 1
  results_folder: result/result_fastec_ODM
  flow_size: [96, 128]
  ck_path: checkpoint/ODM/fastec_ODM.pt
